name: Web Application CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Choose the PHP version compatible with your project

    # PHP Linting
    - name: PHP Lint
      run: find . -name '*.php' ! -path "./vendor/*" -exec php -l {} \;

    # Set up Node.js (if using ESLint)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the Node.js version if you decide to add ESLint

    # Install Node dependencies (if using ESLint)
    - name: Install Node dependencies
      run: npm install

    # JavaScript Linting (if using ESLint)
    - name: Lint JavaScript files
      run: npx eslint *.js

  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          # Your deployment script here
          echo "Deploying to server..."
          # Add your specific deployment commands here
